### model
model_name_or_path: /home/export/base/ycsc_chenkh/hitici_02/online1/enhance_alignment/LLaMA-Factory/saves/llama2-7b/full/baseline/QAalign_1st-stage_full_sft

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: llama2_metamath_2nd-stage_data
template: empty
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/export/base/ycsc_chenkh/hitici_02/online1/enhance_alignment/LLaMA-Factory/saves/llama2-7b/full/baseline/QAalign_2nd-stage_full_sft
logging_steps: 10
save_steps: 0
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000