### model
model_name_or_path: /home/export/base/ycsc_chenkh/hitici_02/online1/data/pretrained-models/Llama-2-7b

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/export/base/ycsc_chenkh/hitici_02/online1/AlignSFT/LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: llama2_openmath2_2nd-stage_data
template: empty
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/export/base/ycsc_chenkh/hitici_02/online1/AlignSFT/LLaMA-Factory/saves/llama2-7b/full/baseline/llama2_baseline_openmath2_full_sft
logging_steps: 10
save_steps: 1000
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
weight_decay: 0.01
num_train_epochs: 2.0
lr_scheduler_type: constant
warmup_steps: 0
bf16: true
ddp_timeout: 180000000